# Generated by Django 5.1.1 on 2024-10-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('initiator', models.CharField(max_length=100)),
                ('participants', models.CharField(blank=True, max_length=200)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('current_members', models.PositiveIntegerField(default=0)),
                ('total_members', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
